<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

#### Exercise 1

| **Term** | **Brief description** |
| :--- | :--- |
| Subsetting | To select something |
| Indexing | To select an element from a list |
| Slicing | To select a range of elements from a list |
| Masking | When answering questions in true/ false formats, masking can be used to obtain elements which would give a True result to the question asked |

#### Exercise 2

In [1]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
py_list2d = np_array_2d
py_list2d[:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [2]:
np_array_sub = np.array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'])
int_array = np_array_sub.astype(int)
int_array

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [3]:
np_array_modulo = int_array % 2
np_array_modulo

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [8]:
my_mask = np_array_modulo != 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [13]:
np_array_2d[my_mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [16]:
np_array_3d = np_array_2d[my_mask]

odd_letters = np_array_3d[:,1]
odd_letters

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')