<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

#### Python list

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]   
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#### Numpy Arrays

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#### Dictionary 

In [3]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [5]:
py_real_names[0]

'Natasha Romanoff'

In [6]:
py_super_names[0]

'Black Widow'

In [7]:
py_super_names[2]

'Doctor Strange'

In [8]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [9]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [10]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [11]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [12]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [13]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

Lists:

In [15]:
len(py_list_2d)

10

Arrays:

In [16]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [17]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

Lists:

In [18]:
py_list

[1, 1.5, 'A']

Arrays:

In [19]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  # to create a new NumPy array using the Python list

Arrays

In [21]:
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [23]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [24]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [26]:
np_array*2

array([ 2,  4,  6,  8, 10])

In [27]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## 2.6 Squaring

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [29]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [31]:
py_list == 3     #Qn: Are all the numbers in the list 3?

False

In [32]:
np_array == 3

array([False, False,  True, False, False])

In [33]:
np_array>3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [35]:
sum(py_list)

15

In [36]:
max(py_list)

5

In [37]:
min(py_list)

1

In [38]:
np_array.sum()

15

In [39]:
np_array.max()

5

In [40]:
np_array.min()

1

In [41]:
np_array.mean()

3.0

In [42]:
np_array.std()

1.4142135623730951

## Footnotes