<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- Subsetting: to select
- Indexing: selecting one element
- Slicing: selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
x = py_list

In [4]:
x[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [5]:
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

Slicing in python
- Slicing with [i:j], the slice will start at i and end at j-1, giving you a total of j-i elements

## 1.2 Arrays only | Subsetting by masking

**Only works with Numpy arrays**

In [6]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
np_array[~(np_array > 3)] 

array([1, 2, 3])

In [10]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [11]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [12]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [13]:
py_list_2d[3]

[4, 'D']

In [14]:
py_list_2d[3][0]

4

In [15]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [16]:
py_list_2d[:3][0]

[1, 'A']

In [17]:
py_list_2d[3:6][0]

[4, 'D']

## 1.4 Growing lists

In [18]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [19]:
x=[1]              #adding one element at a time
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [20]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [21]:
a=(1, 2, 3) #defining
print(a[0]) #accessing data

1


## 1.6 Be VERY careful when copying

In [22]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

Completed. Under storing_data_(good)_exercises

## Footnotes